# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af64081488fa79b9db94d9886dbeb82b8caedec781dc82b7b9bf81c3a01ff93dfe20959332aa1a4b0eb55eec5f57d8e4977f3b34dd0014dc323a8406bf5caf19

test:
  secret_key_base: 94306dc27a7266904d78ba606ffa0c85825265855207e4ed460e818bbded289df1b930140ea5d2c0f5ef1d0a9caa65086c589d48deea0570bbf831f46b46aa8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
